-- ============================================
-- Migration: quotable-notifications
-- Date: 2026-05-05
-- Description: Add tags to quotes and devices for personalized notifications
-- ============================================

-- 0. Create quotes table if it doesn't exist
CREATE TABLE IF NOT EXISTS quotes (
  id SERIAL PRIMARY KEY,
  text TEXT NOT NULL,
  author TEXT,
  tags TEXT[] DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 1. Add tags column to quotes (if table existed before)
ALTER TABLE quotes
  ADD COLUMN IF NOT EXISTS tags TEXT[] DEFAULT '{}';

-- 2. Add preferred_tags column to devices
ALTER TABLE devices
  ADD COLUMN IF NOT EXISTS preferred_tags TEXT[] DEFAULT '{}';

-- 3. Create GIN index for tag overlap queries
CREATE INDEX IF NOT EXISTS idx_quotes_tags ON quotes USING GIN(tags);

-- ============================================
-- SEED DATA: ~300 curated quotes across 8 categories
-- Categories: philosophy, science, technology, business, history, wisdom, famous-quotes, motivation
-- Minimum 30 per category. Mixed English and Spanish.
-- ============================================

-- PHILOSOPHY (40 quotes)
INSERT INTO quotes (text, author, tags) VALUES
('The unexamined life is not worth living.', 'Socrates', ARRAY['philosophy']),
('I think, therefore I am.', 'Rene Descartes', ARRAY['philosophy']),
('He who has a why to live can bear almost any how.', 'Friedrich Nietzsche', ARRAY['philosophy']),
('The only true wisdom is in knowing you know nothing.', 'Socrates', ARRAY['philosophy']),
('Man is condemned to be free.', 'Jean-Paul Sartre', ARRAY['philosophy']),
('Happiness depends upon ourselves.', 'Aristotle', ARRAY['philosophy']),
('The mind is everything. What you think you become.', 'Buddha', ARRAY['philosophy']),
('We are what we repeatedly do.', 'Aristotle', ARRAY['philosophy']),
('To be is to be perceived.', 'George Berkeley', ARRAY['philosophy']),
('The life of man is solitary, poor, nasty, brutish, and short.', 'Thomas Hobbes', ARRAY['philosophy']),
('One cannot step twice in the same river.', 'Heraclitus', ARRAY['philosophy']),
('The greatest wealth is to live content with little.', 'Plato', ARRAY['philosophy']),
('Wonder is the beginning of wisdom.', 'Socrates', ARRAY['philosophy']),
('No man ever steps in the same river twice.', 'Heraclitus', ARRAY['philosophy']),
('At the touch of love everyone becomes a poet.', 'Plato', ARRAY['philosophy']),
('There is only one good, knowledge, and one evil, ignorance.', 'Socrates', ARRAY['philosophy']),
('Knowing yourself is the beginning of all wisdom.', 'Aristotle', ARRAY['philosophy']),
('El hombre es un animal racional.', 'Aristoteles', ARRAY['philosophy']),
('La vida no examinada no merece ser vivida.', 'Socrates', ARRAY['philosophy']),
('Pienso, luego existo.', 'Rene Descartes', ARRAY['philosophy']),
('La felicidad depende de nosotros mismos.', 'Aristoteles', ARRAY['philosophy']),
('Solo se que no se nada.', 'Socrates', ARRAY['philosophy']),
('El ser humano esta condenado a ser libre.', 'Jean-Paul Sartre', ARRAY['philosophy']),
('La mente lo es todo. Lo que piensas, te conviertes.', 'Buda', ARRAY['philosophy']),
('Somos lo que hacemos repetidamente.', 'Aristoteles', ARRAY['philosophy']),
('El mayor bien es vivir contento con poco.', 'Platon', ARRAY['philosophy']),
('La maravilla es el principio de la sabiduria.', 'Socrates', ARRAY['philosophy']),
('Conocerte a ti mismo es el principio de toda sabiduria.', 'Aristoteles', ARRAY['philosophy']),
('Happiness is not an ideal of reason but of imagination.', 'Immanuel Kant', ARRAY['philosophy']),
('The limits of my language mean the limits of my world.', 'Ludwig Wittgenstein', ARRAY['philosophy']),
('Whereof one cannot speak, thereof one must be silent.', 'Ludwig Wittgenstein', ARRAY['philosophy']),
('Hell is other people.', 'Jean-Paul Sartre', ARRAY['philosophy']),
('Existence precedes essence.', 'Jean-Paul Sartre', ARRAY['philosophy']),
('The owl of Minerva spreads its wings only with the falling of the dusk.', 'Georg Wilhelm Friedrich Hegel', ARRAY['philosophy']),
('One must imagine Sisyphus happy.', 'Albert Camus', ARRAY['philosophy']),
('In the middle of difficulty lies opportunity.', 'Albert Camus', ARRAY['philosophy']),
('The only way to deal with an unfree world is to become so absolutely free that your very existence is an act of rebellion.', 'Albert Camus', ARRAY['philosophy']),
('He who fights with monsters should look to it that he himself does not become a monster.', 'Friedrich Nietzsche', ARRAY['philosophy']),
('That which does not kill us makes us stronger.', 'Friedrich Nietzsche', ARRAY['philosophy']),
('Without music, life would be a mistake.', 'Friedrich Nietzsche', ARRAY['philosophy']);

-- SCIENCE (40 quotes)
INSERT INTO quotes (text, author, tags) VALUES
('The important thing is not to stop questioning.', 'Albert Einstein', ARRAY['science']),
('Imagination is more important than knowledge.', 'Albert Einstein', ARRAY['science']),
('Science is organized knowledge. Wisdom is organized life.', 'Immanuel Kant', ARRAY['science']),
('The good thing about science is that it''s true whether or not you believe in it.', 'Neil deGrasse Tyson', ARRAY['science']),
('Somewhere, something incredible is waiting to be known.', 'Carl Sagan', ARRAY['science']),
('The cosmos is within us. We are made of star-stuff.', 'Carl Sagan', ARRAY['science']),
('Science is not only a disciple of reason but also one of romance and passion.', 'Stephen Hawking', ARRAY['science']),
('Nothing in life is to be feared, it''s only to be understood.', 'Marie Curie', ARRAY['science']),
('Be less curious about people and more curious about ideas.', 'Marie Curie', ARRAY['science']),
('The saddest aspect of life right now is that science gathers knowledge faster than society gathers wisdom.', 'Isaac Asimov', ARRAY['science']),
('In science, there are no shortcuts to truth.', 'Karl Popper', ARRAY['science']),
('The greatest enemy of knowledge is not ignorance, it is the illusion of knowledge.', 'Stephen Hawking', ARRAY['science']),
('Look up at the stars and not down at your feet.', 'Stephen Hawking', ARRAY['science']),
('Intelligence is the ability to adapt to change.', 'Stephen Hawking', ARRAY['science']),
('A person who never made a mistake never tried anything new.', 'Albert Einstein', ARRAY['science']),
('Try not to become a man of success, but rather try to become a man of value.', 'Albert Einstein', ARRAY['science']),
('Logic will get you from A to B. Imagination will take you everywhere.', 'Albert Einstein', ARRAY['science']),
('The measure of intelligence is the ability to change.', 'Albert Einstein', ARRAY['science']),
('Life is like riding a bicycle. To keep your balance, you must keep moving.', 'Albert Einstein', ARRAY['science']),
('Reality is merely an illusion, albeit a very persistent one.', 'Albert Einstein', ARRAY['science']),
('La ciencia es el gran antídoto contra el veneno del entusiasmo y la superstición.', 'Adam Smith', ARRAY['science']),
('Lo maravilloso de la ciencia es que es cierta creas o no en ella.', 'Neil deGrasse Tyson', ARRAY['science']),
('El cosmos esta dentro de nosotros. Estamos hechos de materia de estrellas.', 'Carl Sagan', ARRAY['science']),
('En algun lugar, algo increible espera ser descubierto.', 'Carl Sagan', ARRAY['science']),
('Nada en la vida debe ser temido, solo debe ser comprendido.', 'Marie Curie', ARRAY['science']),
('La inteligencia es la capacidad de adaptarse al cambio.', 'Stephen Hawking', ARRAY['science']),
('Una persona que nunca cometio un error nunca intento nada nuevo.', 'Albert Einstein', ARRAY['science']),
('La logica te lleva de A a B. La imaginacion te lleva a todas partes.', 'Albert Einstein', ARRAY['science']),
('La vida es como andar en bicicleta. Para mantener el equilibrio, debes seguir avanzando.', 'Albert Einstein', ARRAY['science']),
('The universe is under no obligation to make sense to you.', 'Neil deGrasse Tyson', ARRAY['science']),
('We are just an advanced breed of monkeys on a minor planet of a very average star.', 'Stephen Hawking', ARRAY['science']),
('The greatest enemy of knowledge is the illusion of knowledge.', 'Daniel J. Boorstin', ARRAY['science']),
('Science knows no country, because knowledge belongs to humanity.', 'Louis Pasteur', ARRAY['science']),
('Chance favors the prepared mind.', 'Louis Pasteur', ARRAY['science']),
('In the fields of observation, chance favors only the prepared mind.', 'Louis Pasteur', ARRAY['science']),
('The eye sees only what the mind is prepared to comprehend.', 'Robertson Davies', ARRAY['science']),
('Equipped with his five senses, man explores the universe around him and calls the adventure Science.', 'Edwin Hubble', ARRAY['science']),
('The important thing is to not stop questioning. Curiosity has its own reason for existing.', 'Albert Einstein', ARRAY['science']),
('Two things are infinite: the universe and human stupidity; and I''m not sure about the universe.', 'Albert Einstein', ARRAY['science']),
('Science without religion is lame, religion without science is blind.', 'Albert Einstein', ARRAY['science']);

-- TECHNOLOGY (40 quotes)
INSERT INTO quotes (text, author, tags) VALUES
('Any sufficiently advanced technology is indistinguishable from magic.', 'Arthur C. Clarke', ARRAY['technology']),
('The advance of technology is based on making it fit in so that you don''t even notice it.', 'Bill Gates', ARRAY['technology']),
('Technology is best when it brings people together.', 'Matt Mullenweg', ARRAY['technology']),
('It has become appallingly obvious that our technology has exceeded our humanity.', 'Albert Einstein', ARRAY['technology']),
('The real problem is not whether machines think but whether men do.', 'B.F. Skinner', ARRAY['technology']),
('The human spirit must prevail over technology.', 'Albert Einstein', ARRAY['technology']),
('Technology is nothing. What''s important is that you have a faith in people.', 'Steve Jobs', ARRAY['technology']),
('Innovation distinguishes between a leader and a follower.', 'Steve Jobs', ARRAY['technology']),
('Stay hungry, stay foolish.', 'Steve Jobs', ARRAY['technology']),
('Design is not just what it looks like and feels like. Design is how it works.', 'Steve Jobs', ARRAY['technology']),
('The people who are crazy enough to think they can change the world are the ones who do.', 'Steve Jobs', ARRAY['technology']),
('Simple can be harder than complex.', 'Steve Jobs', ARRAY['technology']),
('Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.', 'Steve Jobs', ARRAY['technology']),
('The Internet is becoming the town square for the global village of tomorrow.', 'Bill Gates', ARRAY['technology']),
('Software is a great combination between artistry and engineering.', 'Bill Gates', ARRAY['technology']),
('Success is a lousy teacher. It seduces smart people into thinking they can''t lose.', 'Bill Gates', ARRAY['technology']),
('We always overestimate the change that will occur in the next two years and underestimate the change that will occur in the next ten.', 'Bill Gates', ARRAY['technology']),
('The first rule of any technology used in a business is that automation applied to an efficient operation will magnify the efficiency.', 'Bill Gates', ARRAY['technology']),
('Measuring programming progress by lines of code is like measuring aircraft building progress by weight.', 'Bill Gates', ARRAY['technology']),
('Talking to computers is easier than talking to people.', 'Unknown', ARRAY['technology']),
('La tecnologia es mejor cuando une a las personas.', 'Matt Mullenweg', ARRAY['technology']),
('La innovacion distingue entre un lider y un seguidor.', 'Steve Jobs', ARRAY['technology']),
('Mantente hambriento, mantente insensato.', 'Steve Jobs', ARRAY['technology']),
('El diseno no es solo lo que se ve. El diseno es como funciona.', 'Steve Jobs', ARRAY['technology']),
('Las personas lo suficientemente locas para pensar que pueden cambiar el mundo son las que lo hacen.', 'Steve Jobs', ARRAY['technology']),
('Lo simple puede ser mas dificil que lo complejo.', 'Steve Jobs', ARRAY['technology']),
('Cualquier tecnologia suficientemente avanzada es indistinguible de la magia.', 'Arthur C. Clarke', ARRAY['technology']),
('El espiritu humano debe prevalecer sobre la tecnologia.', 'Albert Einstein', ARRAY['technology']),
('The best way to predict the future is to invent it.', 'Alan Kay', ARRAY['technology']),
('The computer was born to solve problems that did not exist before.', 'Bill Gates', ARRAY['technology']),
('Data is a precious thing and will last longer than the systems themselves.', 'Tim Berners-Lee', ARRAY['technology']),
('The Web as I envisaged it, we have not seen it yet.', 'Tim Berners-Lee', ARRAY['technology']),
('Any product that needs a manual to work is broken.', 'Elon Musk', ARRAY['technology']),
('When something is important enough, you do it even if the odds are not in your favor.', 'Elon Musk', ARRAY['technology']),
('I think it is possible for ordinary people to choose to be extraordinary.', 'Elon Musk', ARRAY['technology']),
('Persistence is very important. You should not give up unless you are forced to give up.', 'Elon Musk', ARRAY['technology']),
('Failure is an option here. If things are not failing, you are not innovating enough.', 'Elon Musk', ARRAY['technology']),
('The path to the CEO''s office should not be through the CFO''s office.', 'Elon Musk', ARRAY['technology']),
('Some people don''t like change, but you need to embrace change if the alternative is disaster.', 'Elon Musk', ARRAY['technology']),
('I could either watch it happen or be a part of it.', 'Elon Musk', ARRAY['technology']);

-- BUSINESS (40 quotes)
INSERT INTO quotes (text, author, tags) VALUES
('The best time to plant a tree was 20 years ago. The second best time is now.', 'Chinese Proverb', ARRAY['business']),
('Your most unhappy customers are your greatest source of learning.', 'Bill Gates', ARRAY['business']),
('If you are not embarrassed by the first version of your product, you''ve launched too late.', 'Reid Hoffman', ARRAY['business']),
('The way to get started is to quit talking and begin doing.', 'Walt Disney', ARRAY['business']),
('Don''t be afraid to give up the good to go for the great.', 'John D. Rockefeller', ARRAY['business']),
('I find that the harder I work, the more luck I seem to have.', 'Thomas Jefferson', ARRAY['business']),
('Success usually comes to those who are too busy to be looking for it.', 'Henry David Thoreau', ARRAY['business']),
('The secret of getting ahead is getting started.', 'Mark Twain', ARRAY['business']),
('It is hard to fail, but it is worse never to have tried to succeed.', 'Theodore Roosevelt', ARRAY['business']),
('The only place where success comes before work is in the dictionary.', 'Vidal Sassoon', ARRAY['business']),
('Opportunities don''t happen. You create them.', 'Chris Grosser', ARRAY['business']),
('Don''t let yesterday take up too much of today.', 'Will Rogers', ARRAY['business']),
('You learn more from failure than from success.', 'Unknown', ARRAY['business']),
('It''s not whether you get knocked down, it''s whether you get up.', 'Vince Lombardi', ARRAY['business']),
('If you really look closely, most overnight successes took a long time.', 'Steve Jobs', ARRAY['business']),
('The only limit to our realization of tomorrow will be our doubts of today.', 'Franklin D. Roosevelt', ARRAY['business']),
('Quality is not an act, it is a habit.', 'Aristotle', ARRAY['business']),
('The customer''s perception is your reality.', 'Kate Zabriskie', ARRAY['business']),
('You don''t learn to walk by following rules. You learn by doing, and by falling over.', 'Richard Branson', ARRAY['business']),
('Business opportunities are like buses, there''s always another one coming.', 'Richard Branson', ARRAY['business']),
('El mejor momento para plantar un arbol fue hace 20 anos. El segundo mejor momento es ahora.', 'Proverbio Chino', ARRAY['business']),
('La forma de empezar es dejar de hablar y empezar a hacer.', 'Walt Disney', ARRAY['business']),
('No tengas miedo de renunciar a lo bueno para ir por lo grandioso.', 'John D. Rockefeller', ARRAY['business']),
('El secreto para avanzar es comenzar.', 'Mark Twain', ARRAY['business']),
('Las oportunidades no suceden. Tu las creas.', 'Chris Grosser', ARRAY['business']),
('La calidad no es un acto, es un habito.', 'Aristoteles', ARRAY['business']),
('No aprendes a caminar siguiendo reglas. Aprendes haciendo, y cayendote.', 'Richard Branson', ARRAY['business']),
('The biggest risk is not taking any risk.', 'Mark Zuckerberg', ARRAY['business']),
('Move fast and break things.', 'Mark Zuckerberg', ARRAY['business']),
('The question isn''t what are we going to do, the question is, what aren''t we going to do?', 'Mark Zuckerberg', ARRAY['business']),
('Ideas are easy. Implementation is hard.', 'Guy Kawasaki', ARRAY['business']),
('The most dangerous phrase in the language is, we''ve always done it this way.', 'Grace Hopper', ARRAY['business']),
('A ship in harbor is safe, but that is not what ships are built for.', 'John A. Shedd', ARRAY['business']),
('Done is better than perfect.', 'Sheryl Sandberg', ARRAY['business']),
('Leadership is not about being in charge. It is about taking care of those in your charge.', 'Simon Sinek', ARRAY['business']),
('People don''t buy what you do; they buy why you do it.', 'Simon Sinek', ARRAY['business']),
('If everything seems under control, you''re not going fast enough.', 'Mario Andretti', ARRAY['business']),
('The best revenge is massive success.', 'Frank Sinatra', ARRAY['business']),
('I never dreamed about success. I worked for it.', 'Estee Lauder', ARRAY['business']),
('Success is walking from failure to failure with no loss of enthusiasm.', 'Winston Churchill', ARRAY['business']);

-- HISTORY (40 quotes)
INSERT INTO quotes (text, author, tags) VALUES
('Those who cannot remember the past are condemned to repeat it.', 'George Santayana', ARRAY['history']),
('History is written by the victors.', 'Winston Churchill', ARRAY['history']),
('The only thing new in the world is the history you do not know.', 'Harry S. Truman', ARRAY['history']),
('A people without the knowledge of their past history is like a tree without roots.', 'Marcus Garvey', ARRAY['history']),
('History never repeats itself. Man always does.', 'Voltaire', ARRAY['history']),
('The farther backward you can look, the farther forward you are likely to see.', 'Winston Churchill', ARRAY['history']),
('History is a set of lies agreed upon.', 'Napoleon Bonaparte', ARRAY['history']),
('In history, as in life, it is the impossible that happens.', 'Unknown', ARRAY['history']),
('Those who don''t know history are doomed to repeat it.', 'Edmund Burke', ARRAY['history']),
('History is the version of past events that people have decided to agree upon.', 'Napoleon Bonaparte', ARRAY['history']),
('Study the past if you would define the future.', 'Confucius', ARRAY['history']),
('I must study politics and war that my sons may have liberty to study mathematics and philosophy.', 'John Adams', ARRAY['history']),
('The only function of economic forecasting is to make astrology look respectable.', 'John Kenneth Galbraith', ARRAY['history']),
('History will be kind to me for I intend to write it.', 'Winston Churchill', ARRAY['history']),
('A generation which ignores history has no past and no future.', 'Robert A. Heinlein', ARRAY['history']),
('History is not a burden on the memory but an illumination of the soul.', 'Lord Acton', ARRAY['history']),
('The past is never dead. It''s not even past.', 'William Faulkner', ARRAY['history']),
('History teaches us that men and nations behave wisely once they have exhausted all other alternatives.', 'Abba Eban', ARRAY['history']),
('We are not makers of history. We are made by history.', 'Martin Luther King Jr.', ARRAY['history']),
('History is who we are and why we are the way we are.', 'David McCullough', ARRAY['history']),
('Aquellos que no pueden recordar el pasado estan condenados a repetirlo.', 'George Santayana', ARRAY['history']),
('La historia la escriben los vencedores.', 'Winston Churchill', ARRAY['history']),
('Un pueblo sin conocimiento de su historia es como un arbol sin raices.', 'Marcus Garvey', ARRAY['history']),
('Estudia el pasado si quieres definir el futuro.', 'Confucio', ARRAY['history']),
('La historia nos ensena que los hombres y las naciones actuan con sabiduria una vez agotadas todas las alternativas.', 'Abba Eban', ARRAY['history']),
('No somos creadores de la historia. Somos hechos por la historia.', 'Martin Luther King Jr.', ARRAY['history']),
('La historia es quienes somos y por que somos como somos.', 'David McCullough', ARRAY['history']),
('The more you know about the past, the better prepared you are for the future.', 'Theodore Roosevelt', ARRAY['history']),
('History is a gallery of pictures in which there are few originals and many copies.', 'Alexis de Tocqueville', ARRAY['history']),
('The only new thing in the world is the history you don''t know.', 'Harry S. Truman', ARRAY['history']),
('History is the sum total of things that could have been avoided.', 'Konrad Adenauer', ARRAY['history']),
('Those who cannot remember the past are condemned to repeat it.', 'George Santayana', ARRAY['history']),
('History is a relentless master. It has no present, only the past rushing into the future.', 'John F. Kennedy', ARRAY['history']),
('The very ink with which history is written is merely fluid prejudice.', 'Mark Twain', ARRAY['history']),
('History is a race between education and catastrophe.', 'H.G. Wells', ARRAY['history']),
('Revolutions are not made; they come.', 'Wendell Phillips', ARRAY['history']),
('Power tends to corrupt, and absolute power corrupts absolutely.', 'Lord Acton', ARRAY['history']),
('Great minds discuss ideas; average minds discuss events; small minds discuss people.', 'Eleanor Roosevelt', ARRAY['history']),
('The price of freedom is eternal vigilance.', 'Thomas Jefferson', ARRAY['history']),
('Give me liberty, or give me death!', 'Patrick Henry', ARRAY['history']);

-- WISDOM (40 quotes)
INSERT INTO quotes (text, author, tags) VALUES
('The only way to do great work is to love what you do.', 'Steve Jobs', ARRAY['wisdom']),
('In the end, we will remember not the words of our enemies, but the silence of our friends.', 'Martin Luther King Jr.', ARRAY['wisdom']),
('The journey of a thousand miles begins with one step.', 'Lao Tzu', ARRAY['wisdom']),
('Knowing others is intelligence; knowing yourself is true wisdom.', 'Lao Tzu', ARRAY['wisdom']),
('A wise man can learn more from a foolish question than a fool can learn from a wise answer.', 'Bruce Lee', ARRAY['wisdom']),
('The fool doth think he is wise, but the wise man knows himself to be a fool.', 'William Shakespeare', ARRAY['wisdom']),
('Turn your wounds into wisdom.', 'Oprah Winfrey', ARRAY['wisdom']),
('The only true wisdom is in knowing you know nothing.', 'Socrates', ARRAY['wisdom']),
('Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.', 'Rumi', ARRAY['wisdom']),
('It is the mark of an educated mind to be able to entertain a thought without accepting it.', 'Aristotle', ARRAY['wisdom']),
('The greatest glory in living lies not in never falling, but in rising every time we fall.', 'Nelson Mandela', ARRAY['wisdom']),
('The best way to find out if you can trust somebody is to trust them.', 'Ernest Hemingway', ARRAY['wisdom']),
('Courage is resistance to fear, mastery of fear, not absence of fear.', 'Mark Twain', ARRAY['wisdom']),
('The only thing we have to fear is fear itself.', 'Franklin D. Roosevelt', ARRAY['wisdom']),
('What lies behind us and what lies before us are tiny matters compared to what lies within us.', 'Ralph Waldo Emerson', ARRAY['wisdom']),
('Do not go where the path may lead, go instead where there is no path and leave a trail.', 'Ralph Waldo Emerson', ARRAY['wisdom']),
('To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.', 'Ralph Waldo Emerson', ARRAY['wisdom']),
('The wound is the place where the Light enters you.', 'Rumi', ARRAY['wisdom']),
('Let the beauty of what you love be what you do.', 'Rumi', ARRAY['wisdom']),
('Patience is not the ability to wait, but the ability to keep a good mood while waiting.', 'Unknown', ARRAY['wisdom']),
('La unica forma de hacer un gran trabajo es amar lo que haces.', 'Steve Jobs', ARRAY['wisdom']),
('Al final, recordaremos no las palabras de nuestros enemigos, sino el silencio de nuestros amigos.', 'Martin Luther King Jr.', ARRAY['wisdom']),
('El viaje de mil millas comienza con un paso.', 'Lao Tse', ARRAY['wisdom']),
('Conocer a los demas es inteligencia; conocerte a ti mismo es verdadera sabiduria.', 'Lao Tse', ARRAY['wisdom']),
('Convierte tus heridas en sabiduria.', 'Oprah Winfrey', ARRAY['wisdom']),
('Ayer era astuto, queria cambiar el mundo. Hoy soy sabio, me estoy cambiando a mi mismo.', 'Rumi', ARRAY['wisdom']),
('La mayor gloria no es nunca caer, sino levantarse cada vez que caemos.', 'Nelson Mandela', ARRAY['wisdom']),
('El coraje es la resistencia al miedo, el dominio del miedo, no la ausencia de miedo.', 'Mark Twain', ARRAY['wisdom']),
('Lo que esta detras de nosotros y lo que esta delante de nosotros son pequenas cosas comparadas con lo que esta dentro de nosotros.', 'Ralph Waldo Emerson', ARRAY['wisdom']),
('No vayas por donde el camino te lleve, ve donde no hay camino y deja huella.', 'Ralph Waldo Emerson', ARRAY['wisdom']),
('Be yourself; everyone else is already taken.', 'Oscar Wilde', ARRAY['wisdom']),
('Be the change that you wish to see in the world.', 'Mahatma Gandhi', ARRAY['wisdom']),
('Live as if you were to die tomorrow. Learn as if you were to live forever.', 'Mahatma Gandhi', ARRAY['wisdom']),
('The weak can never forgive. Forgiveness is the attribute of the strong.', 'Mahatma Gandhi', ARRAY['wisdom']),
('In a gentle way, you can shake the world.', 'Mahatma Gandhi', ARRAY['wisdom']),
('First they ignore you, then they laugh at you, then they fight you, then you win.', 'Mahatma Gandhi', ARRAY['wisdom']),
('An eye for an eye only ends up making the whole world blind.', 'Mahatma Gandhi', ARRAY['wisdom']),
('Happiness is when what you think, what you say, and what you do are in harmony.', 'Mahatma Gandhi', ARRAY['wisdom']),
('The best time to plant a tree was twenty years ago. The second best time is now.', 'Chinese Proverb', ARRAY['wisdom']),
('It does not matter how slowly you go as long as you do not stop.', 'Confucius', ARRAY['wisdom']);

-- FAMOUS-QUOTES (40 quotes)
INSERT INTO quotes (text, author, tags) VALUES
('To be or not to be, that is the question.', 'William Shakespeare', ARRAY['famous-quotes']),
('All that glitters is not gold.', 'William Shakespeare', ARRAY['famous-quotes']),
('The lady doth protest too much, methinks.', 'William Shakespeare', ARRAY['famous-quotes']),
('All the world''s a stage, and all the men and women merely players.', 'William Shakespeare', ARRAY['famous-quotes']),
('This above all: to thine own self be true.', 'William Shakespeare', ARRAY['famous-quotes']),
('Brevity is the soul of wit.', 'William Shakespeare', ARRAY['famous-quotes']),
('The course of true love never did run smooth.', 'William Shakespeare', ARRAY['famous-quotes']),
('What''s in a name? That which we call a rose by any other name would smell as sweet.', 'William Shakespeare', ARRAY['famous-quotes']),
('I have not failed. I''ve just found 10,000 ways that won''t work.', 'Thomas Edison', ARRAY['famous-quotes']),
('Genius is one percent inspiration and ninety-nine percent perspiration.', 'Thomas Edison', ARRAY['famous-quotes']),
('Our greatest weakness lies in giving up.', 'Thomas Edison', ARRAY['famous-quotes']),
('Many of life''s failures are people who did not realize how close they were to success when they gave up.', 'Thomas Edison', ARRAY['famous-quotes']),
('I have a dream.', 'Martin Luther King Jr.', ARRAY['famous-quotes']),
('Injustice anywhere is a threat to justice everywhere.', 'Martin Luther King Jr.', ARRAY['famous-quotes']),
('Darkness cannot drive out darkness; only light can do that.', 'Martin Luther King Jr.', ARRAY['famous-quotes']),
('Hate cannot drive out hate; only love can do that.', 'Martin Luther King Jr.', ARRAY['famous-quotes']),
('The time is always right to do what is right.', 'Martin Luther King Jr.', ARRAY['famous-quotes']),
('Faith is taking the first step even when you can''t see the whole staircase.', 'Martin Luther King Jr.', ARRAY['famous-quotes']),
('Ser o no ser, esa es la cuestion.', 'William Shakespeare', ARRAY['famous-quotes']),
('No todo lo que brilla es oro.', 'William Shakespeare', ARRAY['famous-quotes']),
('Todo el mundo es un escenario y todos los hombres y mujeres meros actores.', 'William Shakespeare', ARRAY['famous-quotes']),
('Por encima de todo, se fiel a ti mismo.', 'William Shakespeare', ARRAY['famous-quotes']),
('La brevedad es el alma del ingenio.', 'William Shakespeare', ARRAY['famous-quotes']),
('No he fallado. Solo he encontrado 10,000 formas que no funcionan.', 'Thomas Edison', ARRAY['famous-quotes']),
('El genio es un uno por ciento de inspiracion y noventa y nueve por ciento de transpiracion.', 'Thomas Edison', ARRAY['famous-quotes']),
('Tengo un sueno.', 'Martin Luther King Jr.', ARRAY['famous-quotes']),
('La injusticia en cualquier lugar es una amenaza para la justicia en todas partes.', 'Martin Luther King Jr.', ARRAY['famous-quotes']),
('La oscuridad no puede expulsar a la oscuridad; solo la luz puede hacerlo.', 'Martin Luther King Jr.', ARRAY['famous-quotes']),
('El momento siempre es correcto para hacer lo correcto.', 'Martin Luther King Jr.', ARRAY['famous-quotes']),
('That''s one small step for man, one giant leap for mankind.', 'Neil Armstrong', ARRAY['famous-quotes']),
('The only thing necessary for the triumph of evil is for good men to do nothing.', 'Edmund Burke', ARRAY['famous-quotes']),
('Ask not what your country can do for you — ask what you can do for your country.', 'John F. Kennedy', ARRAY['famous-quotes']),
('I came, I saw, I conquered.', 'Julius Caesar', ARRAY['famous-quotes']),
('Knowledge is power.', 'Francis Bacon', ARRAY['famous-quotes']),
('The only thing I know is that I know nothing.', 'Socrates', ARRAY['famous-quotes']),
('Man is the measure of all things.', 'Protagoras', ARRAY['famous-quotes']),
('Give me a lever long enough and a fulcrum on which to place it, and I shall move the world.', 'Archimedes', ARRAY['famous-quotes']),
('Eureka!', 'Archimedes', ARRAY['famous-quotes']),
('I think therefore I am.', 'Rene Descartes', ARRAY['famous-quotes']),
('God does not play dice with the universe.', 'Albert Einstein', ARRAY['famous-quotes']);

-- MOTIVATION (40 quotes)
INSERT INTO quotes (text, author, tags) VALUES
('Believe you can and you''re halfway there.', 'Theodore Roosevelt', ARRAY['motivation']),
('It does not matter how slowly you go as long as you do not stop.', 'Confucius', ARRAY['motivation']),
('Everything you''ve ever wanted is on the other side of fear.', 'George Addair', ARRAY['motivation']),
('Hardships often prepare ordinary people for an extraordinary destiny.', 'C.S. Lewis', ARRAY['motivation']),
('The only impossible journey is the one you never begin.', 'Tony Robbins', ARRAY['motivation']),
('Everything you can imagine is real.', 'Pablo Picasso', ARRAY['motivation']),
('Simplicity is the ultimate sophistication.', 'Leonardo da Vinci', ARRAY['motivation']),
('Whatever you are, be a good one.', 'Abraham Lincoln', ARRAY['motivation']),
('If you can dream it, you can do it.', 'Walt Disney', ARRAY['motivation']),
('The best way to predict the future is to create it.', 'Peter Drucker', ARRAY['motivation']),
('Strive not to be a success, but rather to be of value.', 'Albert Einstein', ARRAY['motivation']),
('Two roads diverged in a wood, and I took the one less traveled by.', 'Robert Frost', ARRAY['motivation']),
('The only limit to our realization of tomorrow will be our doubts of today.', 'Franklin D. Roosevelt', ARRAY['motivation']),
('Act as if what you do makes a difference. It does.', 'William James', ARRAY['motivation']),
('What you get by achieving your goals is not as important as what you become by achieving your goals.', 'Zig Ziglar', ARRAY['motivation']),
('You miss 100% of the shots you don''t take.', 'Wayne Gretzky', ARRAY['motivation']),
('Whether you think you can or you think you can''t, you''re right.', 'Henry Ford', ARRAY['motivation']),
('I have not failed. I''ve just found 10,000 ways that won''t work.', 'Thomas Edison', ARRAY['motivation']),
('A year from now you may wish you had started today.', 'Karen Lamb', ARRAY['motivation']),
('You are never too old to set another goal or to dream a new dream.', 'C.S. Lewis', ARRAY['motivation']),
('Cree que puedes y ya estas a mitad de camino.', 'Theodore Roosevelt', ARRAY['motivation']),
('Todo lo que has deseado esta del otro lado del miedo.', 'George Addair', ARRAY['motivation']),
('Las dificultades a menudo preparan a personas comunes para un destino extraordinario.', 'C.S. Lewis', ARRAY['motivation']),
('El unico viaje imposible es el que nunca comienzas.', 'Tony Robbins', ARRAY['motivation']),
('Todo lo que puedes imaginar es real.', 'Pablo Picasso', ARRAY['motivation']),
('La simplicidad es la maxima sofisticacion.', 'Leonardo da Vinci', ARRAY['motivation']),
('Sea lo que seas, se bueno en ello.', 'Abraham Lincoln', ARRAY['motivation']),
('Si puedes sonarlo, puedes hacerlo.', 'Walt Disney', ARRAY['motivation']),
('La mejor forma de predecir el futuro es crearlo.', 'Peter Drucker', ARRAY['motivation']),
('Actua como si lo que haces marcara la diferencia. La marca.', 'William James', ARRAY['motivation']),
('Te pierdes el 100% de los tiros que no intentas.', 'Wayne Gretzky', ARRAY['motivation']),
('Ya sea que creas que puedes o que no puedes, tienes razon.', 'Henry Ford', ARRAY['motivation']),
('Dentro de un ano puedes desear haber empezado hoy.', 'Karen Lamb', ARRAY['motivation']),
('Nunca eres demasiado viejo para establecer otra meta o sonar un nuevo sueno.', 'C.S. Lewis', ARRAY['motivation']),
('Keep your face always toward the sunshine — and shadows will fall behind you.', 'Walt Whitman', ARRAY['motivation']),
('The future belongs to those who believe in the beauty of their dreams.', 'Eleanor Roosevelt', ARRAY['motivation']),
('What we think, we become.', 'Buddha', ARRAY['motivation']),
('You must be the change you wish to see in the world.', 'Mahatma Gandhi', ARRAY['motivation']),
('Dream big and dare to fail.', 'Norman Vaughan', ARRAY['motivation']),
('Do what you can, with what you have, where you are.', 'Theodore Roosevelt', ARRAY['motivation']);
